In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
# One hot enconding for each char in 'hello'
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [3]:
with tf.variable_scope('one_cell') as scope:
    # One cell RNN input_dim (4) -> output_dim (2)
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
    pp.pprint(x_data)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2
array([[[ 1.,  0.,  0.,  0.]]], dtype=float32)
array([[[-0.34310868,  0.63254935]]], dtype=float32)


In [4]:
pp.pprint(_states.eval())

array([[-0.34310868,  0.63254935]], dtype=float32)


In [5]:
with tf.variable_scope('two_sequances') as scope:
    # One cell RNN input_dim (4) -> output_dim(2).  sequence: 5
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype = np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)
array([[[ 0.412146  , -0.69913411],
        [ 0.844455  ,  0.01900602],
        [ 0.03718993, -0.1701005 ],
        [-0.5261209 ,  0.24237718],
        [-0.87348777, -0.46253327]]], dtype=float32)


In [6]:
with tf.variable_scope('3_batches') as scope:
    # One cell RNN input_dim(4) -> output_dim(2).  sequence: 5, batch 3
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[-0.07940529, -0.01423988],
        [-0.04485764,  0.09821821],
        [-0.1072259 ,  0.19449247],
        [-0.1484853 ,  0.27138552],
        [-0.18550169,  0.26227668]],

       [[ 0.00728407,  0.09841535],
        [ 0.03158922,  0.03646006],
        [-0.08057542,  0.13449715],
        [-0.13329653,  0.22769116],
        [-0.1624386 ,  0.29520786]],

       [[-0.08712462,  0.11139396],
        [-0.13605204,  0.21151087],
        [-0.11809996,  0.28654501],
        [-0.08051027,  0.33023953],
        [-0.12625293,

In [9]:
with tf.variable_scope('3_batches_dynamic') as scope:
    # One cell RNN input_dim(4) -> output_dim(2).  sequence: 5, batch 3
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)

    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data,
                    sequence_length=[5,3,4], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.01433176, -0.03674208],
        [ 0.03987009,  0.05545969],
        [-0.07087167,  0.0907432 ],
        [-0.12889814,  0.12957479],
        [-0.16102119,  0.09344037]],

       [[ 0.02989668,  0.09829217],
        [ 0.02544419,  0.058792  ],
        [-0.0800654 ,  0.1122072 ],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[-0.08952112,  0.04144859],
        [-0.14042319,  0.08369851],
        [-0.11508805,  0.18268995],
        [-0.04165398,  0.26150236],
        [ 0.        ,

In [11]:
with tf.variable_scope('initial_state') as scope:
    # One cell RNN input_dim(4) -> output_dim(2).  sequence: 5, batch 3
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    
    batch_size = 3
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)

    pp.pprint(x_data)
    initial_state = cell.zero_state(batch_size, tf.float32)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data,
                    initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[-0.05352102,  0.11182348],
        [ 0.02658509,  0.08201865],
        [ 0.07902616,  0.17522691],
        [ 0.10362837,  0.23431666],
        [ 0.09964754,  0.19210619]],

       [[ 0.05116956,  0.02905277],
        [ 0.08612381,  0.08854985],
        [ 0.11933634,  0.17801693],
        [ 0.13219805,  0.240328  ],
        [ 0.14445952,  0.28259549]],

       [[ 0.04379521,  0.10362003],
        [ 0.07689333,  0.18213044],
        [ 0.07656586,  0.13288195],
        [ 0.09721275,  0.11995953],
        [ 0.17078625,

In [12]:
# Create input data
batch_size = 3
sequence_length = 5
input_dim = 3
x_data = np.arange(45, dtype=np.float32).reshape(batch_size,
                                        sequence_length, input_dim)
pp.pprint(x_data)

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.],
        [  9.,  10.,  11.],
        [ 12.,  13.,  14.]],

       [[ 15.,  16.,  17.],
        [ 18.,  19.,  20.],
        [ 21.,  22.,  23.],
        [ 24.,  25.,  26.],
        [ 27.,  28.,  29.]],

       [[ 30.,  31.,  32.],
        [ 33.,  34.,  35.],
        [ 36.,  37.,  38.],
        [ 39.,  40.,  41.],
        [ 42.,  43.,  44.]]], dtype=float32)


In [13]:
with tf.variable_scope('generated_data') as scope:
    cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
    initial_state = cell.zero_state(batch_size, tf.float32)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data,
                            initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[  3.51299681e-02,   1.14920340e-01,  -4.61310521e-02,
          -2.89094418e-01,   2.21141979e-01],
        [  1.09116308e-01,   6.33198023e-01,  -1.61162335e-02,
          -4.33102578e-01,   4.00112242e-01],
        [  1.06331922e-01,   9.23635185e-01,  -2.00067111e-03,
          -3.09051752e-01,   3.55902731e-01],
        [  7.74010196e-02,   9.87921059e-01,  -1.14773262e-04,
          -1.41718373e-01,   2.47329324e-01],
        [  5.07289134e-02,   9.98227596e-01,  -6.11745327e-06,
          -5.48894443e-02,   1.50091887e-01]],

       [[  2.25980650e-03,   7.60111272e-01,  -3.87793904e-07,
          -3.07179373e-02,   4.97445837e-02],
        [  2.20530597e-03,   9.63702619e-01,  -2.56002082e-08,
          -1.18744569e-02,   4.57143225e-02],
        [  1.66986778e-03,   9.95005488e-01,  -1.67555547e-09,
          -5.20331739e-03,   2.83862520e-02],
        [  1.17153302e-03,   9.99322414e-01,  -1.10372204e-10,
          -2.47730408e-03,   1.62278730e-02],
        [  7.9775

In [14]:
with tf.variable_scope('MultiRNNCell') as scope:
    # make run
    cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
    cell = rnn.MultiRNNCell([cell] * 3, state_is_tuple=True)
    # rnn in/out
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    print("dynamic rnn:", outputs)
    sess.run(tf.globla_variables_initializer())
    pp.pprint(outputs.eval())

ValueError: Trying to share variable MultiRNNCell/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (10, 20) and found shape (8, 20).